/**
 * Gateway Module
 *
 * Unified entry point exposing A2UI WebSocket, MCP, and REST APIs.
 * AgentOS: All UI is generated by Agent via A2UI protocol.
 */

export * from './server.js';
export * from './a2ui.js';
export * from './mcp.js';
export * from './pages.js';
