/**
 * Gateway Server
 *
 * Bun-based HTTP + WebSocket server exposing A2UI, MCP, and REST APIs.
 * AgentOS Architecture: All UI is generated by Agent via A2UI protocol.
 */

import { Hono } from "hono";
import { cors } from "hono/cors";
import { mcpHandler } from "./mcp.js";
import { createPHAAgent, type PHAAgent } from "../agent/pha-agent.js";
import { getDataSource } from "../tools/health-data.js";
import { createDataSourceForUser } from "../data-sources/index.js";
import { t } from "../locales/index.js";
import type { HealthDataSource } from "../data-sources/interface.js";
import { loadConfig, getUserUuid } from "../utils/config.js";
import { installFetchInterceptor } from "../utils/llm-logger.js";
import { getMemoryManager } from "../memory/index.js";

// Install fetch interceptor to log raw LLM API requests/responses
installFetchInterceptor();
import { huaweiAuth } from "../data-sources/huawei/huawei-auth.js";
import { getUserStore } from "../data-sources/huawei/user-store.js";
import {
  startOAuthSession,
  completeOAuth,
  getHuaweiAuthUrl,
} from "../services/huawei-oauth-service.js";
import { runOAuthFlowWithChrome } from "../services/chrome-mcp-client.js";
import {
  generateChatPage,
  generateHealthPage,
  generateSleepPage,
  generateActivityPage,
  generateMemoryPage,
  generatePromptsPage,
  generateSkillsPage,
  generateEvolutionPage,
  generateBenchmarkRunDetailModal,
  generatePage,
  generateToast,
  generateTraceDetailModal,
  generateEvaluationDetailModal,
  generateTestCaseDetailModal,
  generateSuggestionDetailModal,
  generateCreateTestCaseModal,
  generateCreateSkillModal,
  generatePromptRevertModal,
  generateAuthRequiredPage,
  generateBenchmarkProgress,
  generateBenchmarkProgressComplete,
  generateToolCards,
  mergePendingCards,
  generateIntegrationsPage,
} from "./pages.js";
import { ProgressiveDashboardLoader } from "./progressive-loader.js";
import { loadMemorySummary, getRecentDailyLogs } from "../memory/profile.js";
import {
  listPromptsTool,
  getPromptTool,
  getPromptHistoryTool,
  updatePromptTool,
  revertPromptTool,
} from "../tools/prompt-tools.js";
import {
  listSkillsTool,
  getSkillTool,
  toggleSkillTool,
  updateSkillTool,
  createSkillTool,
} from "../tools/skill-tools.js";
import {
  listTraces,
  countTraces,
  getTrace,
  getEvaluationStats,
  getEvaluation,
  getEvaluationByTraceId,
  listEvaluations,
  listTestCases,
  getTestCase,
  listSuggestions,
  getSuggestion,
  insertTestCase,
  deleteTestCase,
  updateSuggestionStatus,
  listBenchmarkRuns,
  listCategoryScores,
  getBenchmarkRun,
} from "../memory/db.js";
import { BenchmarkRunner } from "../evolution/benchmark-runner.js";

export interface GatewayConfig {
  port?: number;
  apiKey?: string;
  provider?: "anthropic" | "openai" | "google" | "openrouter" | "groq" | "mistral" | "xai";
  modelId?: string;
  baseUrl?: string;
}

// WebSocket message types
interface WSMessage {
  type: string;
  [key: string]: unknown;
}

interface WSInitMessage extends WSMessage {
  type: "init";
}

interface WSNavigateMessage extends WSMessage {
  type: "navigate";
  view: string;
}

interface WSUserMessage extends WSMessage {
  type: "user_message";
  content: string;
}

interface WSActionMessage extends WSMessage {
  type: "action";
  action: string;
  payload?: Record<string, unknown>;
}

/**
 * Create the Gateway Hono app (HTTP routes only)
 */
export function createGatewayApp() {
  const app = new Hono();

  // CORS
  app.use("/*", cors());

  // Health check
  app.get("/health", (c) => c.json({ status: "ok" }));

  // MCP endpoints
  app.post("/mcp/tools/list", async (c) => {
    const tools = mcpHandler.listTools();
    return c.json({ tools });
  });

  app.post("/mcp/tools/call", async (c) => {
    const body = await c.req.json();
    const result = await mcpHandler.callTool({
      name: body.name,
      arguments: body.arguments || {},
    });
    return c.json(result);
  });

  // Slack webhook endpoint
  app.post("/api/integrations/slack/webhook", async (c) => {
    try {
      const body = await c.req.json();
      const { handleSlackWebhook } = await import("../integrations/slack-webhook.js");
      const result = await handleSlackWebhook(body);
      return c.json({
        response_type: "in_channel",
        text: result.issueUrl
          ? `Feedback received! Issue created: ${result.issueUrl}`
          : `Feedback received and classified as: ${result.classification.category} (${result.classification.severity})${result.error ? ` [Note: ${result.error}]` : ""}`,
      });
    } catch (error) {
      return c.json(
        {
          response_type: "ephemeral",
          text: `Error processing feedback: ${error instanceof Error ? error.message : String(error)}`,
        },
        500
      );
    }
  });

  // REST API endpoints for health data
  app.get("/api/health/summary", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;

    const [metrics, heartRate, sleep, workouts] = await Promise.all([
      dataSource.getMetrics(actualDate),
      dataSource.getHeartRate(actualDate),
      dataSource.getSleep(actualDate),
      dataSource.getWorkouts(actualDate),
    ]);

    return c.json({
      date: actualDate,
      metrics,
      heartRate,
      sleep,
      workouts,
    });
  });

  app.get("/api/health/metrics", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const metrics = await dataSource.getMetrics(actualDate);
    return c.json(metrics);
  });

  app.get("/api/health/heart-rate", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const heartRate = await dataSource.getHeartRate(actualDate);
    return c.json(heartRate);
  });

  app.get("/api/health/sleep", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const sleep = await dataSource.getSleep(actualDate);
    return c.json(sleep || { message: "No sleep data available" });
  });

  app.get("/api/health/workouts", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const workouts = await dataSource.getWorkouts(actualDate);
    return c.json(workouts);
  });

  app.get("/api/health/weekly", async (c) => {
    const dataSource = getDataSource();
    const today = new Date().toISOString().split("T")[0];
    const [weeklySteps, weeklySleep] = await Promise.all([
      dataSource.getWeeklySteps(today),
      dataSource.getWeeklySleep(today),
    ]);
    return c.json({ weeklySteps, weeklySleep });
  });

  // ============================================================================
  // OAuth Endpoints
  // ============================================================================

  /**
   * Start OAuth flow - redirect to Huawei authorization page
   */
  app.get("/auth/huawei/start", (c) => {
    const uuid = c.req.query("uuid");
    if (!uuid) {
      return c.json({ error: "Missing UUID" }, 400);
    }

    const config = loadConfig();
    const huaweiConfig = config.dataSources.huawei;

    if (!huaweiConfig?.clientId) {
      return c.html(
        generateOAuthErrorPage("Huawei client ID not configured. Run 'pha huawei setup' first.")
      );
    }

    // Use the gateway callback URL
    const port = config.gateway.port || 8000;
    const redirectUri = huaweiConfig.redirectUri || `http://localhost:${port}/auth/huawei/callback`;

    // Get auth URL with state parameter for CSRF protection and UUID passing
    const authUrl = huaweiAuth.getAuthUrl(huaweiConfig.clientId, redirectUri);
    const urlWithState = `${authUrl}&state=${encodeURIComponent(uuid)}`;

    return c.redirect(urlWithState);
  });

  /**
   * OAuth callback - exchange code for tokens and store
   */
  app.get("/auth/huawei/callback", async (c) => {
    const code = c.req.query("code");
    const state = c.req.query("state"); // UUID passed via state

    if (!code) {
      return c.html(generateOAuthErrorPage("Missing authorization code"));
    }

    if (!state) {
      return c.html(generateOAuthErrorPage("Missing state parameter"));
    }

    const uuid = decodeURIComponent(state);

    try {
      const config = loadConfig();
      const huaweiConfig = config.dataSources.huawei;

      if (!huaweiConfig?.clientId || !huaweiConfig?.clientSecret) {
        return c.html(generateOAuthErrorPage("Huawei credentials not configured"));
      }

      const port = config.gateway.port || 8000;
      const redirectUri =
        huaweiConfig.redirectUri || `http://localhost:${port}/auth/huawei/callback`;

      // Exchange code for token
      const token = await huaweiAuth.exchangeCodeForUser(
        code,
        huaweiConfig.clientId,
        huaweiConfig.clientSecret,
        redirectUri
      );

      // Store token in user store (SQLite)
      const userStore = getUserStore();
      userStore.saveToken(uuid, token);

      return c.html(generateOAuthSuccessPage());
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      return c.html(generateOAuthErrorPage(message));
    }
  });

  /**
   * Check OAuth status for a user
   */
  app.get("/auth/huawei/status", (c) => {
    const uuid = c.req.query("uuid");
    if (!uuid) {
      return c.json({ authenticated: false });
    }

    const userStore = getUserStore();
    const authenticated = userStore.isAuthenticated(uuid);
    const token = userStore.getToken(uuid);

    return c.json({
      authenticated,
      expiresAt: token?.expiresAt,
      needsRefresh: authenticated ? userStore.needsRefresh(uuid) : undefined,
    });
  });

  /**
   * Get OAuth URL for browser extension flow
   * Returns the Huawei OAuth URL that the extension should open
   */
  app.get("/auth/huawei/get-auth-url", (c) => {
    const uuid = c.req.query("uuid");
    if (!uuid) {
      return c.json({ error: "Missing UUID" }, 400);
    }

    const config = loadConfig();
    const huaweiConfig = config.dataSources.huawei;

    if (!huaweiConfig?.clientId) {
      return c.json({ error: "Huawei client ID not configured" }, 400);
    }

    const authUrl = getHuaweiAuthUrl(uuid);
    return c.json({ authUrl });
  });

  /**
   * Exchange authorization code for token (used by browser extension)
   */
  app.post("/auth/huawei/exchange", async (c) => {
    const body = await c.req.json().catch(() => ({}));
    const { code, uuid } = body;

    if (!code || !uuid) {
      return c.json({ success: false, error: "Missing code or uuid" }, 400);
    }

    const config = loadConfig();
    const huaweiConfig = config.dataSources.huawei;

    if (!huaweiConfig?.clientId || !huaweiConfig?.clientSecret) {
      return c.json({ success: false, error: "Huawei credentials not configured" }, 400);
    }

    try {
      const redirectUri = huaweiConfig.redirectUri || "hms://redirect_url";

      const token = await huaweiAuth.exchangeCodeForUser(
        code,
        huaweiConfig.clientId,
        huaweiConfig.clientSecret,
        redirectUri
      );

      const userStore = getUserStore();
      userStore.saveToken(uuid, token);

      console.log(`[OAuth Extension] Successfully authenticated user ${uuid.slice(0, 8)}`);
      return c.json({ success: true });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`[OAuth Extension] Error:`, message);
      return c.json({ success: false, error: message }, 500);
    }
  });

  /**
   * Chrome MCP OAuth flow - automates browser login using Chrome DevTools MCP
   *
   * This endpoint:
   * 1. Launches Chrome via chrome-devtools-mcp
   * 2. Opens Huawei OAuth page
   * 3. Waits for user to complete login
   * 4. Captures authorization code from redirect URL (hms://redirect_url?code=xxx)
   * 5. Exchanges code for token and stores it
   */
  app.post("/auth/huawei/mcp-flow", async (c) => {
    const body = await c.req.json().catch(() => ({}));
    const uuid = body.uuid;

    if (!uuid) {
      return c.json({ success: false, error: "Missing UUID" }, 400);
    }

    const config = loadConfig();
    const huaweiConfig = config.dataSources.huawei;

    if (!huaweiConfig?.clientId || !huaweiConfig?.clientSecret) {
      return c.json(
        {
          success: false,
          error: "Huawei credentials not configured. Run 'pha huawei setup' first.",
        },
        400
      );
    }

    // Generate auth URL with state parameter
    const authUrl = getHuaweiAuthUrl(uuid);
    console.log(`[OAuth MCP] Starting Chrome MCP flow for user ${uuid.slice(0, 8)}...`);
    console.log(`[OAuth MCP] Auth URL: ${authUrl.slice(0, 100)}...`);

    try {
      // Run OAuth flow with Chrome MCP
      const result = await runOAuthFlowWithChrome(authUrl, { timeout: 180000 });

      if ("error" in result) {
        console.error(`[OAuth MCP] Flow failed:`, result.error);
        return c.json({ success: false, error: result.error }, 400);
      }

      // Exchange code for token directly (no session needed for MCP flow)
      const port = config.gateway.port || 8000;
      const redirectUri = huaweiConfig.redirectUri || "hms://redirect_url";

      const token = await huaweiAuth.exchangeCodeForUser(
        result.code,
        huaweiConfig.clientId,
        huaweiConfig.clientSecret,
        redirectUri
      );

      // Store token in user store (SQLite)
      const userStore = getUserStore();
      userStore.saveToken(uuid, token);

      console.log(`[OAuth MCP] Successfully authenticated user ${uuid.slice(0, 8)}`);
      return c.json({ success: true });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`[OAuth MCP] Error:`, message);
      return c.json({ success: false, error: message }, 500);
    }
  });

  return app;
}

/**
 * Generate OAuth success HTML page
 */
function generateOAuthSuccessPage(): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Authorization Successful</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      margin: 0;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
    }
    .container {
      text-align: center;
      padding: 40px;
      background: rgba(255, 255, 255, 0.1);
      border-radius: 16px;
      backdrop-filter: blur(10px);
    }
    .icon {
      font-size: 64px;
      margin-bottom: 20px;
    }
    h1 {
      margin: 0 0 10px 0;
      font-weight: 600;
    }
    p {
      margin: 0;
      opacity: 0.9;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="icon">✓</div>
    <h1>Authorization Successful</h1>
    <p>Closing this window...</p>
  </div>
  <script>
    setTimeout(() => window.close(), 1500);
  </script>
</body>
</html>`;
}

/**
 * Generate OAuth error HTML page
 */
function generateOAuthErrorPage(message: string): string {
  // Escape HTML to prevent XSS
  const escapedMessage = message
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Authorization Failed</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      margin: 0;
      background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
      color: white;
    }
    .container {
      text-align: center;
      padding: 40px;
      background: rgba(255, 255, 255, 0.1);
      border-radius: 16px;
      backdrop-filter: blur(10px);
      max-width: 400px;
    }
    .icon {
      font-size: 64px;
      margin-bottom: 20px;
    }
    h1 {
      margin: 0 0 10px 0;
      font-weight: 600;
    }
    p {
      margin: 0 0 20px 0;
      opacity: 0.9;
    }
    button {
      background: white;
      color: #ef4444;
      border: none;
      padding: 12px 24px;
      border-radius: 8px;
      font-size: 16px;
      cursor: pointer;
      font-weight: 500;
    }
    button:hover {
      background: #f3f4f6;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="icon">✕</div>
    <h1>Authorization Failed</h1>
    <p>${escapedMessage}</p>
    <button onclick="window.close()">Close</button>
  </div>
</body>
</html>`;
}

/**
 * Gateway Session - Manages a single WebSocket session
 * AgentOS: Session manages chat state and generates all UI via A2UI
 */
export class GatewaySession {
  private agent: PHAAgent | null = null;
  private config: GatewayConfig;
  private sessionId: string;
  private dataSource: HealthDataSource;

  // User identification (from cookie)
  public userUuid: string | null = null;

  // Chat state
  private chatMessages: Array<{
    role: "user" | "assistant" | "tool";
    content: string;
    cards?: { components: unknown[]; root_id: string };
  }> = [];
  private pendingCards: Array<{ components: unknown[]; root_id: string }> = [];
  private isStreaming = false;
  private streamingContent = "";
  private currentView = "chat";

  // Settings state
  private selectedPrompt: string | null = null;
  private selectedSkill: string | null = null;
  private editingPrompt = false;
  private editingSkill = false;
  private editBuffer: string | null = null;
  private evolutionTab:
    | "overview"
    | "traces"
    | "evaluations"
    | "benchmark"
    | "runs"
    | "suggestions"
    | "config" = "overview";
  private tracesPage = 0;
  private benchmarkRunning = false;

  // Dashboard state
  private dashboardTab: "overview" | "vitals" | "activity" | "sleep" | "body" | "heart" | "trends" =
    "overview";
  private dashboardLoader: ProgressiveDashboardLoader | null = null;
  private trendsMetric: string = "steps";
  private trendsRange: string = "1m";

  // Integrations page state
  private integrationsTab: "overview" | "issues" | "prs" | "branches" = "overview";
  private integrationsCache: {
    repo?: unknown;
    issues?: unknown[];
    prs?: unknown[];
    branchInfo?: unknown;
    ghAvailable: boolean;
    timestamp: number;
  } | null = null;

  // Memory page state
  private memoryTab: "profile" | "summary" | "logs" | "search" = "profile";
  private memorySearchQuery: string | undefined;
  private memorySearchResults: import("../memory/types.js").MemorySearchResult[] | undefined;

  constructor(config: GatewayConfig = {}, userUuid?: string) {
    this.config = config;
    this.sessionId = crypto.randomUUID();
    this.userUuid = userUuid || getUserUuid();

    // Use user-specific data source if userUuid is provided
    if (userUuid) {
      this.dataSource = createDataSourceForUser(userUuid);
    } else {
      this.dataSource = getDataSource();
    }
  }

  /**
   * Check if the current user is authenticated with Huawei
   */
  isUserAuthenticated(): boolean {
    if (!this.userUuid) return false;
    const config = loadConfig();
    if (config.dataSources.type !== "huawei") return true; // Mock data doesn't need auth
    return huaweiAuth.isUserAuthenticated(this.userUuid);
  }

  private async getAgent(): Promise<PHAAgent> {
    if (!this.agent) {
      this.agent = await createPHAAgent({
        apiKey: this.config.apiKey,
        provider: this.config.provider,
        modelId: this.config.modelId,
        baseUrl: this.config.baseUrl,
        userUuid: this.userUuid || undefined,
        sessionId: this.sessionId,
        dataSource: this.dataSource,
      });
    }
    return this.agent;
  }

  /**
   * Handle incoming WebSocket message
   */
  async handleMessage(data: WSMessage, send: (msg: unknown) => void): Promise<void> {
    switch (data.type) {
      case "init":
        await this.handleInit(send);
        break;
      case "navigate":
        await this.handleNavigate((data as WSNavigateMessage).view, send);
        break;
      case "user_message":
        await this.handleUserMessage((data as WSUserMessage).content, send);
        break;
      case "action":
        await this.handleAction(
          (data as WSActionMessage).action,
          (data as WSActionMessage).payload,
          send
        );
        break;
      case "ping":
        send({ type: "pong" });
        break;
      default:
        console.warn("Unknown message type:", data.type);
    }
  }

  private async handleInit(send: (msg: unknown) => void): Promise<void> {
    send({
      type: "connected",
      session_id: this.sessionId,
    });

    // Send initial UI - default to chat view
    this.currentView = "chat";
    const chatPage = generateChatPage({
      messages: this.chatMessages,
      streaming: this.isStreaming,
      streamingContent: this.streamingContent,
    });
    send(generatePage("chat", chatPage));
  }

  private async handleNavigate(view: string, send: (msg: unknown) => void): Promise<void> {
    this.currentView = view;
    const today = new Date().toISOString().split("T")[0];

    let mainPage;

    switch (view) {
      case "chat":
        mainPage = generateChatPage({
          messages: this.chatMessages,
          streaming: this.isStreaming,
          streamingContent: this.streamingContent,
        });
        break;

      case "dashboard":
      case "health":
      case "sleep":
      case "activity": {
        // Check if user needs to authenticate (only for Huawei data source)
        const config = loadConfig();
        if (config.dataSources.type === "huawei" && !this.isUserAuthenticated()) {
          mainPage = generateAuthRequiredPage();
          break;
        }

        // Map legacy views to dashboard tabs
        if (view === "health") this.dashboardTab = "vitals";
        else if (view === "sleep") this.dashboardTab = "sleep";
        else if (view === "activity") this.dashboardTab = "activity";

        // Use progressive loader for dashboard
        if (!this.dashboardLoader) {
          this.dashboardLoader = new ProgressiveDashboardLoader(this.dataSource, send);
        } else {
          // Update send function in case WebSocket reconnected
          this.dashboardLoader.updateSend(send);
        }

        // Load data progressively — this sends updates directly via send()
        await this.dashboardLoader.load(this.dashboardTab);

        // Return early — progressive loader already sent the page
        return;
      }

      case "memory": {
        // Send loading page immediately
        send(
          generatePage(
            view,
            generateMemoryPage({
              activeTab: this.memoryTab,
              profileCompleteness: 0,
              profile: {} as never,
              missingFields: [],
              memoryStats: { totalChunks: 0, lastUpdated: 0 },
              memorySummary: "",
              dailyLogs: [],
              loading: true,
            })
          )
        );

        // Load data async and re-send
        const mm = getMemoryManager();
        const uuid = this.userUuid || getUserUuid();
        try {
          const memoryPage = generateMemoryPage({
            activeTab: this.memoryTab,
            profileCompleteness: mm.getProfileCompleteness(uuid),
            profile: mm.getProfile(uuid),
            missingFields: mm.getAllMissingFields(uuid).map((f) => f.key),
            memoryStats: mm.getMemoryStats(uuid),
            memorySummary: loadMemorySummary(uuid) || "",
            dailyLogs: getRecentDailyLogs(uuid, 7),
            searchQuery: this.memorySearchQuery,
            searchResults: this.memorySearchResults,
          });
          send(generatePage(view, memoryPage));
        } catch (e) {
          console.error("[Memory] Load error:", e);
        }
        return;
      }

      case "settings/prompts": {
        // Send loading page immediately
        send(
          generatePage(
            view,
            generatePromptsPage({
              prompts: [],
              editing: false,
              loading: true,
            })
          )
        );

        // Fetch data async
        try {
          const promptsResult = await listPromptsTool.execute({});
          let content: string | undefined;
          let commits:
            | Array<{
                hash: string;
                shortHash: string;
                message: string;
                date: string;
                author: string;
              }>
            | undefined;

          if (this.selectedPrompt) {
            const promptResult = await getPromptTool.execute({ name: this.selectedPrompt });
            if (promptResult.success) {
              content = this.editBuffer ?? promptResult.content;
            }

            const historyResult = await getPromptHistoryTool.execute({
              name: this.selectedPrompt,
              limit: 10,
            });
            if (historyResult.success && historyResult.commits) {
              commits = historyResult.commits;
            }
          }

          send(
            generatePage(
              view,
              generatePromptsPage({
                prompts: promptsResult.prompts || [],
                selectedPrompt: this.selectedPrompt || undefined,
                content,
                commits,
                editing: this.editingPrompt,
              })
            )
          );
        } catch (e) {
          console.error("[Prompts] Load error:", e);
        }
        return;
      }

      case "settings/skills": {
        // Send loading page immediately
        send(
          generatePage(
            view,
            generateSkillsPage({
              skills: [],
              editing: false,
              loading: true,
            })
          )
        );

        // Fetch data async
        try {
          const skillsResult = await listSkillsTool.execute({});
          let content: string | undefined;

          if (this.selectedSkill) {
            const skillResult = await getSkillTool.execute({ name: this.selectedSkill });
            if (skillResult.success && "content" in skillResult) {
              content = this.editBuffer ?? skillResult.content;
            }
          }

          send(
            generatePage(
              view,
              generateSkillsPage({
                skills: skillsResult.skills || [],
                selectedSkill: this.selectedSkill || undefined,
                content,
                editing: this.editingSkill,
              })
            )
          );
        } catch (e) {
          console.error("[Skills] Load error:", e);
        }
        return;
      }

      case "settings/evolution": {
        // Send loading page immediately
        send(
          generatePage(
            view,
            generateEvolutionPage({
              activeTab: this.evolutionTab,
              loading: true,
            })
          )
        );

        // Fetch data and re-send
        try {
          const evoData = this.loadEvolutionData();
          send(generatePage(view, generateEvolutionPage(evoData)));
        } catch (e) {
          console.error("[Evolution] Load error:", e);
        }
        return;
      }

      case "settings/integrations": {
        // Send loading page immediately (no data yet)
        send(
          generatePage(
            view,
            generateIntegrationsPage({
              activeTab: this.integrationsTab,
              ghAvailable: true,
              loading: true,
            })
          )
        );

        // Fetch GitHub data async and re-send
        this.loadIntegrationsAsync(send).catch((e) => {
          console.error("[Integrations] Load error:", e);
        });
        return;
      }

      default:
        mainPage = generateChatPage({
          messages: this.chatMessages,
          streaming: this.isStreaming,
          streamingContent: this.streamingContent,
        });
    }

    send(generatePage(view, mainPage));
  }

  private async handleUserMessage(content: string, send: (msg: unknown) => void): Promise<void> {
    // Add user message to chat history
    this.chatMessages.push({ role: "user", content });
    this.isStreaming = true;
    this.streamingContent = "";

    // Extract profile info from user message (non-blocking)
    if (this.userUuid) {
      try {
        const mm = getMemoryManager();
        const extracted = mm.extractAndUpdateProfile(this.userUuid, content);
        if (Object.keys(extracted).length > 0) {
          const fields = Object.keys(extracted).join(", ");
          this.chatMessages.push({ role: "tool", content: `💾 已提取档案: ${fields}` });
          this.sendChatUpdate(send);
        }
      } catch {
        // Profile extraction is best-effort
      }
    }

    // Send updated chat UI immediately
    this.sendChatUpdate(send);

    try {
      const agent = await this.getAgent();

      // Subscribe to agent events
      const unsubscribe = agent.subscribe((event) => {
        this.handleAgentEvent(event, send);
      });

      try {
        await agent.chat(content);
        await agent.getAgent().waitForIdle();
      } finally {
        unsubscribe();
      }
    } catch (error) {
      this.isStreaming = false;
      this.chatMessages.push({
        role: "assistant",
        content: `Error: ${error instanceof Error ? error.message : String(error)}`,
      });
      this.sendChatUpdate(send);

      console.error(`[Agent Error] Session ${this.sessionId}:`, error);

      send({
        type: "error",
        code: "agent_error",
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }

  private sendChatUpdate(send: (msg: unknown) => void): void {
    if (this.currentView === "chat") {
      const chatPage = generateChatPage({
        messages: this.chatMessages,
        streaming: this.isStreaming,
        streamingContent: this.streamingContent,
      });
      send({
        type: "a2ui",
        surface_id: "main",
        components: chatPage.components,
        root_id: chatPage.root_id,
      });
    }
  }

  private async handleAction(
    action: string,
    payload: Record<string, unknown> | undefined,
    send: (msg: unknown) => void
  ): Promise<void> {
    // Handle UI actions (button clicks, form submissions, etc.)
    if (action === "send_message" && payload?.content) {
      // Chat message from UI
      await this.handleUserMessage(payload.content as string, send);
    } else if (action.startsWith("navigate:")) {
      const view = action.replace("navigate:", "");
      await this.handleNavigate(view, send);
    }
    // OAuth actions
    else if (action === "start_huawei_auth" || action === "start_reauth") {
      // Clear scope error cache so re-auth can fix them
      import("../data-sources/huawei/huawei-api.js").then(({ clearMissingScopeErrors }) =>
        clearMissingScopeErrors()
      );
      // The frontend handles opening the OAuth popup
      // We just need to send back confirmation and the user UUID
      send({
        type: "auth_start",
        provider: "huawei",
        userUuid: this.userUuid,
      });
    } else if (action === "set_user_uuid" && payload?.uuid) {
      // Update the session's user UUID (sent from frontend after generating/loading from cookie)
      this.userUuid = payload.uuid as string;
      // Reset agent so it gets recreated with memory context on next message
      this.agent = null;
      send({ type: "user_uuid_set", uuid: this.userUuid });
    } else if (action === "auth_complete") {
      // User completed OAuth — full reset: clear all caches and re-fetch from scratch
      const { clearMemoryCache } = await import("../data-sources/huawei/api-cache.js");
      const { clearMissingScopeErrors } = await import("../data-sources/huawei/huawei-api.js");
      clearMemoryCache();
      clearMissingScopeErrors();
      // Force dashboard loader to start fresh (discard stale null data)
      this.dashboardLoader = null;
      await this.handleNavigate(this.currentView, send);
    }
    // Memory search action
    else if (action === "memory_search_submit" && payload?.query) {
      const mm = getMemoryManager();
      const uuid = this.userUuid || getUserUuid();
      this.memorySearchQuery = payload.query as string;
      this.memorySearchResults = await mm.searchAsync(uuid, this.memorySearchQuery);
      await this.handleNavigate("memory", send);
    } else if (action === "show_toast" && payload?.message) {
      // Show a toast notification
      const variant = (payload.variant as "info" | "success" | "error") || "info";
      const toast = generateToast(payload.message as string, variant);
      send({
        type: "a2ui",
        surface_id: "toast",
        components: toast.components,
        root_id: toast.root_id,
      });
    }
    // Prompts actions
    else if (action === "select_prompt" && payload?.row) {
      const row = payload.row as { name: string };
      this.selectedPrompt = row.name;
      this.editingPrompt = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "edit_prompt") {
      this.editingPrompt = true;
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "cancel_edit") {
      this.editingPrompt = false;
      this.editingSkill = false;
      this.editBuffer = null;
      await this.handleNavigate(this.currentView, send);
    } else if (action === "prompt_content_change" && payload?.value) {
      this.editBuffer = payload.value as string;
    } else if (action === "save_prompt" && this.selectedPrompt && this.editBuffer) {
      await updatePromptTool.execute({
        name: this.selectedPrompt,
        content: this.editBuffer,
        commitMessage: `Update ${this.selectedPrompt} via UI`,
      });
      this.editingPrompt = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "select_commit" && payload?.hash) {
      // Preview commit - could show diff in future
      console.log("Selected commit:", payload.hash);
    }
    // Skills actions
    else if (action === "select_skill" && payload?.row) {
      const row = payload.row as { name: string };
      // Extract skill name (remove emoji prefix)
      const name = row.name.replace(/^[^\s]+\s+/, "");
      this.selectedSkill = name;
      this.editingSkill = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/skills", send);
    } else if (action === "edit_skill") {
      this.editingSkill = true;
      await this.handleNavigate("settings/skills", send);
    } else if (action === "skill_content_change" && payload?.value) {
      this.editBuffer = payload.value as string;
    } else if (action === "save_skill" && this.selectedSkill && this.editBuffer) {
      await updateSkillTool.execute({
        name: this.selectedSkill,
        content: this.editBuffer,
      });
      this.editingSkill = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/skills", send);
    } else if (action === "toggle_skill" && this.selectedSkill) {
      const skillsResult = await listSkillsTool.execute({});
      const skill = skillsResult.skills?.find(
        (s: { name: string }) => s.name === this.selectedSkill
      );
      if (skill) {
        await toggleSkillTool.execute({
          name: this.selectedSkill,
          enabled: !skill.enabled,
        });
        await this.handleNavigate("settings/skills", send);
      }
    } else if (action === "create_skill") {
      // Show create skill modal
      const modal = generateCreateSkillModal();
      send({
        type: "a2ui",
        surface_id: "modal",
        components: modal.components,
        root_id: modal.root_id,
      });
    } else if (action === "submit_create_skill" && payload) {
      const name = payload.name as string;
      const description = payload.description as string;
      const emoji = payload.emoji as string | undefined;
      const triggersStr = payload.triggers as string | undefined;
      const content = payload.content as string | undefined;
      const triggers = triggersStr
        ? triggersStr
            .split(",")
            .map((t) => t.trim())
            .filter(Boolean)
        : undefined;

      await createSkillTool.execute({ name, description, emoji, triggers, content });
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/skills", send);
    }
    // Evolution actions
    else if (action === "tab_change" && payload?.tab) {
      if (
        this.currentView === "dashboard" ||
        this.currentView === "health" ||
        this.currentView === "sleep" ||
        this.currentView === "activity"
      ) {
        type DashboardTab =
          | "overview"
          | "vitals"
          | "activity"
          | "sleep"
          | "body"
          | "heart"
          | "trends";
        this.dashboardTab = payload.tab as DashboardTab;
        if (this.dashboardLoader) {
          this.dashboardLoader.updateSend(send);
          // Pre-set trends state so selectors show current values
          if (this.dashboardTab === "trends") {
            this.dashboardLoader.getData().trendsMetric = this.trendsMetric;
            this.dashboardLoader.getData().trendsRange = this.trendsRange;
          }
          await this.dashboardLoader.load(this.dashboardTab);
          // After loading Trends tab skeleton, load actual trend data
          if (this.dashboardTab === "trends") {
            await this.dashboardLoader.loadTrends(this.trendsMetric, this.trendsRange);
          }
        } else {
          await this.handleNavigate("dashboard", send);
        }
      } else if (this.currentView === "memory") {
        this.memoryTab = payload.tab as "profile" | "summary" | "logs" | "search";
        await this.handleNavigate("memory", send);
      } else if (this.currentView === "settings/integrations") {
        this.integrationsTab = payload.tab as "overview" | "issues" | "prs" | "branches";
        if (this.integrationsCache) {
          // Cache available — instant tab switch
          send(
            generatePage(
              "settings/integrations",
              generateIntegrationsPage({
                activeTab: this.integrationsTab,
                repo: this.integrationsCache.repo as any,
                issues: this.integrationsCache.issues as any,
                prs: this.integrationsCache.prs as any,
                branchInfo: this.integrationsCache.branchInfo as any,
                ghAvailable: this.integrationsCache.ghAvailable,
              })
            )
          );
          this.loadIntegrationsTabData(send).catch(() => {});
        } else {
          // Still loading — just show skeleton for the new tab (don't re-trigger full load)
          send(
            generatePage(
              "settings/integrations",
              generateIntegrationsPage({
                activeTab: this.integrationsTab,
                ghAvailable: true,
                loading: true,
              })
            )
          );
        }
      } else {
        type EvolutionTab =
          | "overview"
          | "traces"
          | "evaluations"
          | "benchmark"
          | "runs"
          | "suggestions"
          | "config";
        this.evolutionTab = payload.tab as EvolutionTab;
        await this.handleNavigate("settings/evolution", send);
      }
    } else if (action === "change_trends_range" && payload) {
      // User changed time range selector
      this.trendsRange = (payload.value as string) || "1m";
      if (this.dashboardLoader) {
        this.dashboardLoader.updateSend(send);
        await this.dashboardLoader.loadTrends(this.trendsMetric, this.trendsRange);
      }
    } else if (action === "change_trends_metric" && payload) {
      // User changed metric selector
      this.trendsMetric = (payload.value as string) || "steps";
      if (this.dashboardLoader) {
        this.dashboardLoader.updateSend(send);
        await this.dashboardLoader.loadTrends(this.trendsMetric, this.trendsRange);
      }
    } else if (action === "trends_config_change" && payload) {
      // Legacy combined handler
      this.trendsMetric = (payload.metric as string) || "steps";
      this.trendsRange = (payload.range as string) || "1m";
      if (this.dashboardLoader) {
        this.dashboardLoader.updateSend(send);
        await this.dashboardLoader.loadTrends(this.trendsMetric, this.trendsRange);
      }
    } else if (action === "traces_page_change" && payload?.page !== undefined) {
      this.tracesPage = payload.page as number;
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "view_trace" && payload?.row) {
      const row = payload.row as { id: string };
      const traceId = row.id.length === 8 ? this.findFullTraceId(row.id) : row.id;
      if (traceId) {
        const trace = getTrace(traceId);
        if (trace) {
          const modal = generateTraceDetailModal({
            id: trace.id,
            sessionId: trace.session_id,
            timestamp: trace.timestamp,
            userMessage: trace.user_message,
            agentResponse: trace.agent_response,
            toolCalls: trace.tool_calls ? JSON.parse(trace.tool_calls) : undefined,
            durationMs: trace.duration_ms || undefined,
          });
          send({
            type: "a2ui",
            surface_id: "modal",
            components: modal.components,
            root_id: modal.root_id,
          });
        }
      }
    } else if (action === "view_evaluation" && payload?.row) {
      const row = payload.row as { id: string; traceId: string };
      const evalId = row.id.length === 8 ? this.findFullEvaluationId(row.id) : row.id;
      if (evalId) {
        const evaluation = getEvaluation(evalId);
        if (evaluation) {
          const modal = generateEvaluationDetailModal({
            id: evaluation.id,
            traceId: evaluation.trace_id,
            timestamp: evaluation.timestamp,
            scores: JSON.parse(evaluation.scores),
            overallScore: evaluation.overall_score,
            feedback: evaluation.feedback || undefined,
            issues: evaluation.issues ? JSON.parse(evaluation.issues) : undefined,
          });
          send({
            type: "a2ui",
            surface_id: "modal",
            components: modal.components,
            root_id: modal.root_id,
          });
        }
      }
    } else if (action === "view_test_case" && payload?.row) {
      const row = payload.row as { id: string };
      const testId = row.id.length === 8 ? this.findFullTestCaseId(row.id) : row.id;
      if (testId) {
        const testCase = getTestCase(testId);
        if (testCase) {
          const modal = generateTestCaseDetailModal({
            id: testCase.id,
            category: testCase.category,
            query: testCase.query,
            context: testCase.context ? JSON.parse(testCase.context) : undefined,
            expected: JSON.parse(testCase.expected),
          });
          send({
            type: "a2ui",
            surface_id: "modal",
            components: modal.components,
            root_id: modal.root_id,
          });
        }
      }
    } else if (action === "view_suggestion" && payload?.row) {
      const row = payload.row as { id: string };
      const suggId = row.id.length === 8 ? this.findFullSuggestionId(row.id) : row.id;
      if (suggId) {
        const suggestion = getSuggestion(suggId);
        if (suggestion) {
          const modal = generateSuggestionDetailModal({
            id: suggestion.id,
            timestamp: suggestion.timestamp,
            type: suggestion.type,
            target: suggestion.target,
            currentValue: suggestion.current_value || undefined,
            suggestedValue: suggestion.suggested_value,
            rationale: suggestion.rationale || undefined,
            status: suggestion.status,
            validationResults: suggestion.validation_results
              ? JSON.parse(suggestion.validation_results)
              : undefined,
          });
          send({
            type: "a2ui",
            surface_id: "modal",
            components: modal.components,
            root_id: modal.root_id,
          });
        }
      }
    } else if (action === "create_test_case") {
      const modal = generateCreateTestCaseModal();
      send({
        type: "a2ui",
        surface_id: "modal",
        components: modal.components,
        root_id: modal.root_id,
      });
    } else if (action === "submit_create_test_case" && payload) {
      const category = payload.category as string;
      const query = payload.query as string;
      const minScore = payload.minScore ? Number(payload.minScore) : undefined;
      const shouldMentionStr = payload.shouldMention as string | undefined;
      const shouldNotMentionStr = payload.shouldNotMention as string | undefined;

      const id = crypto.randomUUID();
      insertTestCase({
        id,
        category,
        query,
        expected: {
          minScore,
          shouldMention: shouldMentionStr
            ? shouldMentionStr
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean)
            : undefined,
          shouldNotMention: shouldNotMentionStr
            ? shouldNotMentionStr
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean)
            : undefined,
        },
      });

      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "delete_test_case" && payload?.id) {
      deleteTestCase(payload.id as string);
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "apply_suggestion" && payload?.id) {
      updateSuggestionStatus(payload.id as string, "applied");
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "reject_suggestion" && payload?.id) {
      updateSuggestionStatus(payload.id as string, "rejected");
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "test_suggestion" && payload?.id) {
      updateSuggestionStatus(payload.id as string, "testing");
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "close_modal") {
      send({ type: "clear_surface", surface_id: "modal" });
    } else if (action === "revert_prompt" && this.selectedPrompt) {
      // Show revert modal with commit history
      const historyResult = await getPromptHistoryTool.execute({
        name: this.selectedPrompt,
        limit: 20,
      });
      if (historyResult.success && historyResult.commits) {
        const modal = generatePromptRevertModal(this.selectedPrompt, historyResult.commits);
        send({
          type: "a2ui",
          surface_id: "modal",
          components: modal.components,
          root_id: modal.root_id,
        });
      }
    } else if (action === "select_revert_commit" && payload?.commit && this.selectedPrompt) {
      const commit = payload.commit as { hash: string };
      await revertPromptTool.execute({ name: this.selectedPrompt, commitHash: commit.hash });
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "run_benchmark") {
      if (this.benchmarkRunning) {
        const toast = generateToast(t("evolution.benchmarkRunning"), "warning");
        send({
          type: "a2ui",
          surface_id: "toast",
          components: toast.components,
          root_id: toast.root_id,
        });
        return;
      }

      const profile = (payload?.profile as "quick" | "full") || "quick";

      // Run benchmark asynchronously (progress shown via progress surface)
      this.runBenchmarkAsync(profile, send).catch(console.error);
    } else if (action === "run_auto_loop") {
      const toast = generateToast(t("evolution.autoLoopHint"), "warning");
      send({
        type: "a2ui",
        surface_id: "toast",
        components: toast.components,
        root_id: toast.root_id,
      });
    } else if (action === "view_benchmark_run" && payload?.row) {
      const row = payload.row as { id: string };
      const runId = this.findFullBenchmarkRunId(row.id);
      if (runId) {
        const run = getBenchmarkRun(runId);
        if (run) {
          const scores = listCategoryScores(runId);
          const modal = generateBenchmarkRunDetailModal(
            {
              id: run.id,
              timestamp: run.timestamp,
              versionTag: run.version_tag,
              profile: run.profile,
              overallScore: run.overall_score,
              passedCount: run.passed_count,
              failedCount: run.failed_count,
              totalTestCases: run.total_test_cases,
              durationMs: run.duration_ms,
            },
            scores.map((s) => ({
              category: s.category,
              score: s.score,
              testCount: s.test_count,
              passedCount: s.passed_count,
            }))
          );
          send({
            type: "a2ui",
            surface_id: "modal",
            components: modal.components,
            root_id: modal.root_id,
          });
        }
      }
    } else if (action === "run_test_case" && payload?.id) {
      const toast = generateToast("Running test case...", "info");
      send({
        type: "a2ui",
        surface_id: "toast",
        components: toast.components,
        root_id: toast.root_id,
      });
      send({ type: "clear_surface", surface_id: "modal" });
      console.log(`Running test case: ${payload.id}`);
    }
    // Integrations actions
    else if (action === "refresh_integrations") {
      this.integrationsCache = null; // Invalidate cache to force refetch
      await this.handleNavigate("settings/integrations", send);
    }
    // Default - pass to agent
    else {
      const message = `[Action: ${action}] ${payload ? JSON.stringify(payload) : ""}`;
      await this.handleUserMessage(message, send);
    }
  }

  // Helper methods to find full IDs from truncated IDs
  private findFullTraceId(shortId: string): string | null {
    const traces = listTraces({ limit: 100 });
    const found = traces.find((t) => t.id.startsWith(shortId));
    return found?.id || null;
  }

  private findFullEvaluationId(shortId: string): string | null {
    const evals = listEvaluations({ limit: 100 });
    const found = evals.find((e) => e.id.startsWith(shortId));
    return found?.id || null;
  }

  private findFullTestCaseId(shortId: string): string | null {
    const tests = listTestCases({ limit: 100 });
    const found = tests.find((t) => t.id.startsWith(shortId));
    return found?.id || null;
  }

  private findFullSuggestionId(shortId: string): string | null {
    const suggs = listSuggestions({ limit: 100 });
    const found = suggs.find((s) => s.id.startsWith(shortId));
    return found?.id || null;
  }

  /**
   * Load integrations data asynchronously and re-send the page.
   * Caches results so tab switches are instant.
   */
  private async loadIntegrationsAsync(send: (msg: unknown) => void): Promise<void> {
    let ghAvailable = true;

    try {
      const { getRepoInfo, listIssues, listPRs, getBranchInfo } =
        await import("../integrations/github.js");

      // Load all data in parallel for caching
      const [repo, issues, prs, branchInfo] = await Promise.all([
        getRepoInfo().catch(() => null),
        listIssues(20).catch(() => []),
        listPRs(20).catch(() => []),
        getBranchInfo().catch(() => undefined),
      ]);

      if (!repo) ghAvailable = false;

      // Cache everything
      this.integrationsCache = {
        repo,
        issues,
        prs,
        branchInfo,
        ghAvailable,
        timestamp: Date.now(),
      };
    } catch {
      ghAvailable = false;
      this.integrationsCache = { ghAvailable: false, timestamp: Date.now() };
    }

    send(
      generatePage(
        "settings/integrations",
        generateIntegrationsPage({
          activeTab: this.integrationsTab,
          repo: this.integrationsCache?.repo as any,
          issues: this.integrationsCache?.issues as any,
          prs: this.integrationsCache?.prs as any,
          branchInfo: this.integrationsCache?.branchInfo as any,
          ghAvailable,
        })
      )
    );
  }

  /**
   * Load tab-specific integrations data that wasn't in the initial cache
   */
  private async loadIntegrationsTabData(send: (msg: unknown) => void): Promise<void> {
    if (!this.integrationsCache) return;

    const { listIssues, listPRs, getBranchInfo } = await import("../integrations/github.js");

    let updated = false;

    if (this.integrationsTab === "issues" && !this.integrationsCache.issues?.length) {
      this.integrationsCache.issues = await listIssues(30).catch(() => []);
      updated = true;
    } else if (this.integrationsTab === "prs" && !this.integrationsCache.prs?.length) {
      this.integrationsCache.prs = await listPRs(20).catch(() => []);
      updated = true;
    } else if (this.integrationsTab === "branches" && !this.integrationsCache.branchInfo) {
      this.integrationsCache.branchInfo = await getBranchInfo().catch(() => undefined);
      updated = true;
    }

    if (updated) {
      send(
        generatePage(
          "settings/integrations",
          generateIntegrationsPage({
            activeTab: this.integrationsTab,
            repo: this.integrationsCache.repo as any,
            issues: this.integrationsCache.issues as any,
            prs: this.integrationsCache.prs as any,
            branchInfo: this.integrationsCache.branchInfo as any,
            ghAvailable: this.integrationsCache.ghAvailable,
          })
        )
      );
    }
  }

  /**
   * Load evolution data synchronously (DB queries are fast)
   */
  private loadEvolutionData() {
    let stats;
    let traces;
    let tracesTotal = 0;
    let evaluations;
    let testCases;
    let suggestions;
    let benchmarkRuns;
    let latestCategoryScores;
    let categoriesConfig;

    if (this.evolutionTab === "overview") {
      stats = getEvaluationStats();
      const runs = listBenchmarkRuns({ limit: 5 });
      benchmarkRuns = runs.map((r) => ({
        id: r.id,
        timestamp: r.timestamp,
        versionTag: r.version_tag,
        profile: r.profile,
        overallScore: r.overall_score,
        passedCount: r.passed_count,
        failedCount: r.failed_count,
        totalTestCases: r.total_test_cases,
        durationMs: r.duration_ms,
        metadata: r.metadata ? JSON.parse(r.metadata) : undefined,
      }));
      if (runs.length > 0) {
        const scores = listCategoryScores(runs[0].id);
        latestCategoryScores = scores.map((s) => ({
          category: s.category,
          score: s.score,
          testCount: s.test_count,
          passedCount: s.passed_count,
        }));
      }
    } else if (this.evolutionTab === "traces") {
      const traceRows = listTraces({ limit: 20, offset: this.tracesPage * 20 });
      tracesTotal = countTraces();
      traces = traceRows.map((t) => {
        const evalResult = getEvaluationByTraceId(t.id);
        return {
          id: t.id,
          timestamp: t.timestamp,
          userMessage: t.user_message,
          score: evalResult?.overall_score,
        };
      });
    } else if (this.evolutionTab === "evaluations") {
      const evalRows = listEvaluations({ limit: 50 });
      evaluations = evalRows.map((e) => ({
        id: e.id,
        traceId: e.trace_id,
        timestamp: e.timestamp,
        score: e.overall_score,
        feedback: e.feedback,
      }));
    } else if (this.evolutionTab === "benchmark") {
      const testRows = listTestCases({ limit: 50 });
      testCases = testRows.map((tc) => ({
        id: tc.id,
        category: tc.category,
        query: tc.query,
        expected: JSON.parse(tc.expected),
      }));
    } else if (this.evolutionTab === "runs") {
      const runs = listBenchmarkRuns({ limit: 20 });
      benchmarkRuns = runs.map((r) => ({
        id: r.id,
        timestamp: r.timestamp,
        versionTag: r.version_tag,
        profile: r.profile,
        overallScore: r.overall_score,
        passedCount: r.passed_count,
        failedCount: r.failed_count,
        totalTestCases: r.total_test_cases,
        durationMs: r.duration_ms,
        metadata: r.metadata ? JSON.parse(r.metadata) : undefined,
      }));
    } else if (this.evolutionTab === "suggestions") {
      const suggRows = listSuggestions({ limit: 50 });
      suggestions = suggRows.map((s) => ({
        id: s.id,
        timestamp: s.timestamp,
        type: s.type,
        target: s.target,
        status: s.status,
        rationale: s.rationale,
      }));
    } else if (this.evolutionTab === "config") {
      const { loadCategoriesConfig } = require("../evolution/benchmark-seed.js");
      categoriesConfig = loadCategoriesConfig();
    }

    return {
      activeTab: this.evolutionTab,
      stats,
      traces,
      tracesPage: this.tracesPage,
      tracesTotal,
      evaluations,
      testCases,
      suggestions,
      benchmarkRuns,
      latestCategoryScores,
      categoriesConfig,
    };
  }

  private findFullBenchmarkRunId(shortId: string): string | null {
    const runs = listBenchmarkRuns({ limit: 100 });
    const found = runs.find((r) => r.id.startsWith(shortId));
    return found?.id || null;
  }

  private async runBenchmarkAsync(
    profile: "quick" | "full",
    send: (msg: unknown) => void
  ): Promise<void> {
    this.benchmarkRunning = true;

    // Show initial progress (current=0)
    const initProgress = generateBenchmarkProgress({
      current: 0,
      total: 0,
      category: "",
      profile,
    });
    send({
      type: "a2ui",
      surface_id: "progress",
      components: initProgress.components,
      root_id: initProgress.root_id,
    });

    try {
      const agent = await this.getAgent();

      const runner = new BenchmarkRunner({
        agentCall: async (query: string) => {
          const response = await agent.chatAndWait(query);
          return { response };
        },
        llmCall: async (prompt: string) => {
          const response = await agent.chatAndWait(prompt);
          return response;
        },
        onProgress: (current, total, testCase) => {
          const progress = generateBenchmarkProgress({
            current,
            total,
            category: testCase.category,
            profile,
          });
          send({
            type: "a2ui",
            surface_id: "progress",
            components: progress.components,
            root_id: progress.root_id,
          });
        },
      });

      // Seed test cases if needed
      await runner.seedTestCases();

      // Run benchmark
      const result = await runner.run({ profile });

      // Show completion progress
      const complete = generateBenchmarkProgressComplete({
        score: result.run.overallScore,
        passed: result.run.passedCount,
        failed: result.run.failedCount,
        total: result.run.totalTestCases,
      });
      send({
        type: "a2ui",
        surface_id: "progress",
        components: complete.components,
        root_id: complete.root_id,
      });

      // Clear progress after 2 seconds
      setTimeout(() => {
        send({ type: "clear_surface", surface_id: "progress" });
      }, 2000);

      // Refresh evolution page
      await this.handleNavigate("settings/evolution", send);
    } catch (error) {
      // Clear progress surface
      send({ type: "clear_surface", surface_id: "progress" });

      const errorToast = generateToast(
        `Benchmark failed: ${error instanceof Error ? error.message : String(error)}`,
        "error"
      );
      send({
        type: "a2ui",
        surface_id: "toast",
        components: errorToast.components,
        root_id: errorToast.root_id,
      });
    } finally {
      this.benchmarkRunning = false;
    }
  }

  private handleAgentEvent(event: any, send: (msg: unknown) => void): void {
    switch (event.type) {
      case "message_start":
      case "message_update":
        // Stream partial content
        if (event.message.role === "assistant") {
          const content = event.message.content;
          let text = "";
          for (const block of content) {
            if (block.type === "text") {
              text += block.text;
            }
          }
          this.streamingContent = text;
          this.sendChatUpdate(send);
          send({ type: "agent_text", content: text, is_final: false });
        }
        break;

      case "message_end":
        if (event.message.role === "assistant") {
          const content = event.message.content;
          let text = "";

          for (const block of content) {
            if (block.type === "text") {
              text += block.text;
            }
          }

          // Check for error responses (API errors, region blocks, etc.)
          if (!text.trim() && event.message.stopReason === "error") {
            const errorMsg = event.message.errorMessage || "Unknown error occurred";
            this.chatMessages.push({
              role: "assistant",
              content: `⚠️ ${errorMsg}`,
            });
            this.isStreaming = false;
            this.streamingContent = "";
            this.pendingCards = [];
            this.sendChatUpdate(send);
            send({ type: "agent_text", content: errorMsg, is_final: true });
            break;
          }

          // Update UI if there's text content
          if (text.trim()) {
            // Attach any pending tool cards to this assistant message
            const cards = mergePendingCards(this.pendingCards);
            this.pendingCards = [];

            this.chatMessages.push({
              role: "assistant",
              content: text,
              ...(cards ? { cards } : {}),
            });
            this.isStreaming = false;
            this.streamingContent = "";
            this.sendChatUpdate(send);
            send({ type: "agent_text", content: text, is_final: true });
          }
        }
        break;

      case "tool_execution_start": {
        const memoryToolLabels: Record<string, string> = {
          memory_search: "🔍 搜索记忆...",
          memory_save: "📝 保存到记忆...",
          daily_log: "📝 记录到今日日志...",
        };
        const toolMsg = memoryToolLabels[event.toolName] || `Using ${event.toolName}...`;
        this.chatMessages.push({ role: "tool", content: toolMsg });
        this.sendChatUpdate(send);
        send({ type: "tool_call", tool: event.toolName });
        break;
      }

      case "tool_execution_end": {
        if (!event.isError) {
          try {
            const cards = generateToolCards(event.toolName, event.result);
            if (cards) {
              this.pendingCards.push(cards);
            }
          } catch (err) {
            console.error(`[ToolCards] Failed to generate cards for ${event.toolName}:`, err);
          }
        }
        break;
      }

      case "agent_end":
        this.isStreaming = false;
        this.sendChatUpdate(send);
        break;
    }
  }
}

// WebSocket data type
interface WSData {
  sessionId: string;
  sessionKey: string;
  config: GatewayConfig;
  userUuid?: string;
}

// Content type helper
function getContentType(filePath: string): string {
  const ext = filePath.split(".").pop()?.toLowerCase();
  const types: Record<string, string> = {
    html: "text/html",
    js: "application/javascript",
    css: "text/css",
    json: "application/json",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    svg: "image/svg+xml",
    ico: "image/x-icon",
    woff: "font/woff",
    woff2: "font/woff2",
    ttf: "font/ttf",
  };
  return types[ext || ""] || "application/octet-stream";
}

/**
 * Start the Gateway server with Bun
 */
export function startGateway(config: GatewayConfig & { webDir?: string } = {}): void {
  const port = config.port || 8000;
  const app = createGatewayApp();
  const sessions = new Map<string, GatewaySession>();
  const webDir = config.webDir;

  Bun.serve<WSData>({
    port,
    async fetch(req, server) {
      const url = new URL(req.url);

      // Upgrade WebSocket connections
      if (url.pathname === "/ws") {
        const sessionId = crypto.randomUUID();

        // Extract user UUID from URL query param (priority) or cookie
        const urlUuid = url.searchParams.get("uuid") || undefined;
        const cookieHeader = req.headers.get("cookie") || "";
        const userUuidMatch = cookieHeader.match(/pha_user_id=([^;]+)/);
        const userUuid = urlUuid || (userUuidMatch ? userUuidMatch[1] : undefined);

        const success = server.upgrade(req, {
          data: { sessionId, sessionKey: userUuid || sessionId, config, userUuid },
        });
        if (success) {
          return undefined;
        }
        return new Response("WebSocket upgrade failed", { status: 400 });
      }

      // Serve static files from web directory
      if (webDir) {
        let filePath = url.pathname;
        if (filePath === "/" || filePath === "") {
          filePath = "/index.html";
        }

        const fullPath = webDir + filePath;
        const file = Bun.file(fullPath);

        if (await file.exists()) {
          const contentType = getContentType(filePath);
          return new Response(file, {
            headers: { "Content-Type": contentType },
          });
        }

        // SPA fallback - serve index.html for non-API routes
        if (
          !filePath.startsWith("/api") &&
          !filePath.startsWith("/mcp") &&
          !filePath.startsWith("/health") &&
          !filePath.startsWith("/auth")
        ) {
          const indexFile = Bun.file(webDir + "/index.html");
          if (await indexFile.exists()) {
            return new Response(indexFile, {
              headers: { "Content-Type": "text/html" },
            });
          }
        }
      }

      // Handle HTTP requests with Hono
      return app.fetch(req);
    },
    websocket: {
      open(ws) {
        const { sessionId, config: wsConfig, userUuid } = ws.data;
        const key = userUuid || sessionId;
        ws.data.sessionKey = key;

        let session = sessions.get(key);
        if (session) {
          console.log(
            `WebSocket reconnected: ${sessionId} → reusing session for ${key.slice(0, 8)}...`
          );
        } else {
          session = new GatewaySession(wsConfig, userUuid);
          sessions.set(key, session);
          console.log(
            `WebSocket connected: ${sessionId}${userUuid ? ` (user: ${userUuid.slice(0, 8)}...)` : ""}`
          );
        }
      },
      async message(ws, message) {
        const session = sessions.get(ws.data.sessionKey);
        if (!session) return;

        try {
          const data = JSON.parse(message.toString());
          await session.handleMessage(data, (msg) => {
            ws.send(JSON.stringify(msg));
          });
        } catch (error) {
          console.error("WebSocket message error:", error);
          ws.send(
            JSON.stringify({
              type: "error",
              code: "parse_error",
              message: "Failed to parse message",
            })
          );
        }
      },
      close(ws) {
        // Don't delete session — keep it alive for reconnection (page refresh)
        console.log(`WebSocket disconnected: ${ws.data.sessionId}`);
      },
    },
  });

  console.log(`PHA Gateway running at http://localhost:${port}`);
  console.log(`WebSocket available at ws://localhost:${port}/ws`);
}

// Legacy export for compatibility
export const createGateway = createGatewayApp;
