/**
 * Gateway Server
 *
 * Bun-based HTTP + WebSocket server exposing A2UI, MCP, and REST APIs.
 * AgentOS Architecture: All UI is generated by Agent via A2UI protocol.
 */

import { Hono } from "hono";
import { cors } from "hono/cors";
import { mcpHandler } from "./mcp.js";
import { createPHAAgent, type PHAAgent } from "../agent/pha-agent.js";
import { getDataSource } from "../tools/health-data.js";
import type { HealthDataSource } from "../data-sources/interface.js";
import {
  generateSidebar,
  generateChatPage,
  generateHealthPage,
  generateSleepPage,
  generateActivityPage,
  generatePromptsPage,
  generateSkillsPage,
  generateEvolutionPage,
  generatePage,
  generateToast,
  generateTraceDetailModal,
  generateEvaluationDetailModal,
  generateTestCaseDetailModal,
  generateSuggestionDetailModal,
  generateCreateTestCaseModal,
  generateCreateSkillModal,
  generatePromptRevertModal,
  type PageMessage,
} from "./pages.js";
import {
  listPromptsTool,
  getPromptTool,
  getPromptHistoryTool,
  updatePromptTool,
  revertPromptTool,
} from "../tools/prompt-tools.js";
import {
  listSkillsTool,
  getSkillTool,
  toggleSkillTool,
  updateSkillTool,
  createSkillTool,
} from "../tools/skill-tools.js";
import {
  listTraces,
  countTraces,
  getTrace,
  getEvaluationStats,
  getEvaluation,
  getEvaluationByTraceId,
  listEvaluations,
  listTestCases,
  getTestCase,
  listSuggestions,
  getSuggestion,
  insertTestCase,
  deleteTestCase,
  updateSuggestionStatus,
} from "../memory/db.js";

export interface GatewayConfig {
  port?: number;
  apiKey?: string;
  provider?: "anthropic" | "openai" | "google" | "openrouter" | "groq" | "mistral" | "xai";
  modelId?: string;
  baseUrl?: string;
}

// WebSocket message types
interface WSMessage {
  type: string;
  [key: string]: unknown;
}

interface WSInitMessage extends WSMessage {
  type: "init";
}

interface WSNavigateMessage extends WSMessage {
  type: "navigate";
  view: string;
}

interface WSUserMessage extends WSMessage {
  type: "user_message";
  content: string;
}

interface WSActionMessage extends WSMessage {
  type: "action";
  action: string;
  payload?: Record<string, unknown>;
}

/**
 * Create the Gateway Hono app (HTTP routes only)
 */
export function createGatewayApp() {
  const app = new Hono();

  // CORS
  app.use("/*", cors());

  // Health check
  app.get("/health", (c) => c.json({ status: "ok" }));

  // MCP endpoints
  app.post("/mcp/tools/list", async (c) => {
    const tools = mcpHandler.listTools();
    return c.json({ tools });
  });

  app.post("/mcp/tools/call", async (c) => {
    const body = await c.req.json();
    const result = await mcpHandler.callTool({
      name: body.name,
      arguments: body.arguments || {},
    });
    return c.json(result);
  });

  // REST API endpoints for health data
  app.get("/api/health/summary", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;

    const [metrics, heartRate, sleep, workouts] = await Promise.all([
      dataSource.getMetrics(actualDate),
      dataSource.getHeartRate(actualDate),
      dataSource.getSleep(actualDate),
      dataSource.getWorkouts(actualDate),
    ]);

    return c.json({
      date: actualDate,
      metrics,
      heartRate,
      sleep,
      workouts,
    });
  });

  app.get("/api/health/metrics", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const metrics = await dataSource.getMetrics(actualDate);
    return c.json(metrics);
  });

  app.get("/api/health/heart-rate", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const heartRate = await dataSource.getHeartRate(actualDate);
    return c.json(heartRate);
  });

  app.get("/api/health/sleep", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const sleep = await dataSource.getSleep(actualDate);
    return c.json(sleep || { message: "No sleep data available" });
  });

  app.get("/api/health/workouts", async (c) => {
    const date = c.req.query("date") || "today";
    const dataSource = getDataSource();
    const actualDate = date === "today" ? new Date().toISOString().split("T")[0] : date;
    const workouts = await dataSource.getWorkouts(actualDate);
    return c.json(workouts);
  });

  app.get("/api/health/weekly", async (c) => {
    const dataSource = getDataSource();
    const today = new Date().toISOString().split("T")[0];
    const [weeklySteps, weeklySleep] = await Promise.all([
      dataSource.getWeeklySteps(today),
      dataSource.getWeeklySleep(today),
    ]);
    return c.json({ weeklySteps, weeklySleep });
  });

  return app;
}

/**
 * Gateway Session - Manages a single WebSocket session
 * AgentOS: Session manages chat state and generates all UI via A2UI
 */
export class GatewaySession {
  private agent: PHAAgent | null = null;
  private config: GatewayConfig;
  private sessionId: string;
  private dataSource: HealthDataSource;

  // Chat state
  private chatMessages: Array<{ role: "user" | "assistant" | "tool"; content: string }> = [];
  private isStreaming = false;
  private streamingContent = "";
  private currentView = "chat";

  // Settings state
  private selectedPrompt: string | null = null;
  private selectedSkill: string | null = null;
  private editingPrompt = false;
  private editingSkill = false;
  private editBuffer: string | null = null;
  private evolutionTab: "overview" | "traces" | "evaluations" | "benchmark" | "suggestions" = "overview";
  private tracesPage = 0;

  constructor(config: GatewayConfig = {}) {
    this.config = config;
    this.sessionId = crypto.randomUUID();
    this.dataSource = getDataSource();
  }

  private getAgent(): PHAAgent {
    if (!this.agent) {
      this.agent = createPHAAgent({
        apiKey: this.config.apiKey,
        provider: this.config.provider,
        modelId: this.config.modelId,
        baseUrl: this.config.baseUrl,
      });
    }
    return this.agent;
  }

  /**
   * Handle incoming WebSocket message
   */
  async handleMessage(data: WSMessage, send: (msg: unknown) => void): Promise<void> {
    switch (data.type) {
      case "init":
        await this.handleInit(send);
        break;
      case "navigate":
        await this.handleNavigate((data as WSNavigateMessage).view, send);
        break;
      case "user_message":
        await this.handleUserMessage((data as WSUserMessage).content, send);
        break;
      case "action":
        await this.handleAction(
          (data as WSActionMessage).action,
          (data as WSActionMessage).payload,
          send
        );
        break;
      case "ping":
        send({ type: "pong" });
        break;
      default:
        console.warn("Unknown message type:", data.type);
    }
  }

  private async handleInit(send: (msg: unknown) => void): Promise<void> {
    send({
      type: "connected",
      session_id: this.sessionId,
    });

    // Send initial UI - default to chat view
    this.currentView = "chat";
    const chatPage = generateChatPage({
      messages: this.chatMessages,
      streaming: this.isStreaming,
      streamingContent: this.streamingContent,
    });
    send(generatePage("chat", chatPage));
  }

  private async handleNavigate(view: string, send: (msg: unknown) => void): Promise<void> {
    this.currentView = view;
    const today = new Date().toISOString().split("T")[0];

    let mainPage;

    switch (view) {
      case "chat":
        mainPage = generateChatPage({
          messages: this.chatMessages,
          streaming: this.isStreaming,
          streamingContent: this.streamingContent,
        });
        break;

      case "health": {
        const [metrics, heartRate] = await Promise.all([
          this.dataSource.getMetrics(today),
          this.dataSource.getHeartRate(today),
        ]);
        mainPage = generateHealthPage({
          heartRate: {
            label: "Heart Rate",
            value: heartRate.restingAvg,
            unit: "bpm resting",
            trend: { direction: "stable", value: "Normal" },
          },
          bloodPressure: {
            label: "Blood Pressure",
            value: "120/80",
            unit: "mmHg",
          },
          spo2: {
            label: "SpO2",
            value: "98%",
            unit: "oxygen",
          },
          heartRateChart: heartRate.readings.slice(-12).map((r) => ({
            label: r.time,
            value: r.value,
          })),
        });
        break;
      }

      case "sleep": {
        const [sleep, weeklySleep] = await Promise.all([
          this.dataSource.getSleep(today),
          this.dataSource.getWeeklySleep(today),
        ]);
        mainPage = generateSleepPage({
          duration: {
            label: "Duration",
            value: sleep?.durationHours || "N/A",
            unit: "hours",
            trend: sleep ? { direction: "stable", value: "On track" } : undefined,
          },
          quality: {
            label: "Quality",
            value: sleep?.qualityScore || "N/A",
            unit: "%",
          },
          deepSleep: {
            label: "Deep Sleep",
            value: sleep?.stages.deep || "N/A",
            unit: "min",
          },
          sleepChart: weeklySleep.map((d) => ({
            label: d.date.slice(-2),
            value: d.hours,
          })),
        });
        break;
      }

      case "activity": {
        const [metrics, weeklySteps] = await Promise.all([
          this.dataSource.getMetrics(today),
          this.dataSource.getWeeklySteps(today),
        ]);
        mainPage = generateActivityPage({
          steps: {
            label: "Steps",
            value: metrics.steps.toLocaleString(),
            unit: "steps today",
            trend: { direction: "up", value: "+12% vs avg" },
          },
          calories: {
            label: "Calories",
            value: metrics.calories.toLocaleString(),
            unit: "kcal burned",
          },
          activeMinutes: {
            label: "Active Time",
            value: metrics.activeMinutes,
            unit: "minutes",
          },
          stepsChart: weeklySteps.map((d) => ({
            label: d.date.slice(-2),
            value: d.steps,
          })),
        });
        break;
      }

      case "settings/prompts": {
        const promptsResult = await listPromptsTool.execute({});
        let content: string | undefined;
        let commits: Array<{ hash: string; shortHash: string; message: string; date: string; author: string }> | undefined;

        if (this.selectedPrompt) {
          const promptResult = await getPromptTool.execute({ name: this.selectedPrompt });
          if (promptResult.success) {
            content = this.editBuffer ?? promptResult.content;
          }

          const historyResult = await getPromptHistoryTool.execute({ name: this.selectedPrompt, limit: 10 });
          if (historyResult.success && historyResult.commits) {
            commits = historyResult.commits;
          }
        }

        mainPage = generatePromptsPage({
          prompts: promptsResult.prompts || [],
          selectedPrompt: this.selectedPrompt || undefined,
          content,
          commits,
          editing: this.editingPrompt,
        });
        break;
      }

      case "settings/skills": {
        const skillsResult = await listSkillsTool.execute({});
        let content: string | undefined;

        if (this.selectedSkill) {
          const skillResult = await getSkillTool.execute({ name: this.selectedSkill });
          if (skillResult.success && "content" in skillResult) {
            content = this.editBuffer ?? skillResult.content;
          }
        }

        mainPage = generateSkillsPage({
          skills: skillsResult.skills || [],
          selectedSkill: this.selectedSkill || undefined,
          content,
          editing: this.editingSkill,
        });
        break;
      }

      case "settings/evolution": {
        let stats;
        let traces;
        let tracesTotal = 0;
        let evaluations;
        let testCases;
        let suggestions;

        if (this.evolutionTab === "overview") {
          stats = getEvaluationStats();
        } else if (this.evolutionTab === "traces") {
          const traceRows = listTraces({ limit: 20, offset: this.tracesPage * 20 });
          tracesTotal = countTraces();
          traces = traceRows.map(t => {
            const evalResult = getEvaluationByTraceId(t.id);
            return {
              id: t.id,
              timestamp: t.timestamp,
              userMessage: t.user_message,
              score: evalResult?.overall_score,
            };
          });
        } else if (this.evolutionTab === "evaluations") {
          const evalRows = listEvaluations({ limit: 50 });
          evaluations = evalRows.map(e => ({
            id: e.id,
            traceId: e.trace_id,
            timestamp: e.timestamp,
            score: e.overall_score,
            feedback: e.feedback,
          }));
        } else if (this.evolutionTab === "benchmark") {
          const testRows = listTestCases({ limit: 50 });
          testCases = testRows.map(tc => ({
            id: tc.id,
            category: tc.category,
            query: tc.query,
            expected: JSON.parse(tc.expected),
          }));
        } else if (this.evolutionTab === "suggestions") {
          const suggRows = listSuggestions({ limit: 50 });
          suggestions = suggRows.map(s => ({
            id: s.id,
            timestamp: s.timestamp,
            type: s.type,
            target: s.target,
            status: s.status,
            rationale: s.rationale,
          }));
        }

        mainPage = generateEvolutionPage({
          activeTab: this.evolutionTab,
          stats,
          traces,
          tracesPage: this.tracesPage,
          tracesTotal,
          evaluations,
          testCases,
          suggestions,
        });
        break;
      }

      default:
        mainPage = generateChatPage({
          messages: this.chatMessages,
          streaming: this.isStreaming,
          streamingContent: this.streamingContent,
        });
    }

    send(generatePage(view, mainPage));
  }

  private async handleUserMessage(content: string, send: (msg: unknown) => void): Promise<void> {
    // Add user message to chat history
    this.chatMessages.push({ role: "user", content });
    this.isStreaming = true;
    this.streamingContent = "";

    // Send updated chat UI immediately
    this.sendChatUpdate(send);

    try {
      const agent = this.getAgent();

      // Subscribe to agent events
      const unsubscribe = agent.subscribe((event) => {
        this.handleAgentEvent(event, send);
      });

      try {
        await agent.chat(content);
        await agent.getAgent().waitForIdle();
      } finally {
        unsubscribe();
      }
    } catch (error) {
      this.isStreaming = false;
      this.chatMessages.push({
        role: "assistant",
        content: `Error: ${error instanceof Error ? error.message : String(error)}`,
      });
      this.sendChatUpdate(send);

      send({
        type: "error",
        code: "agent_error",
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }

  private sendChatUpdate(send: (msg: unknown) => void): void {
    if (this.currentView === "chat") {
      const chatPage = generateChatPage({
        messages: this.chatMessages,
        streaming: this.isStreaming,
        streamingContent: this.streamingContent,
      });
      send({
        type: "a2ui",
        surface_id: "main",
        components: chatPage.components,
        root_id: chatPage.root_id,
      });
    }
  }

  private async handleAction(
    action: string,
    payload: Record<string, unknown> | undefined,
    send: (msg: unknown) => void
  ): Promise<void> {
    // Handle UI actions (button clicks, form submissions, etc.)
    if (action === "send_message" && payload?.content) {
      // Chat message from UI
      await this.handleUserMessage(payload.content as string, send);
    } else if (action.startsWith("navigate:")) {
      const view = action.replace("navigate:", "");
      await this.handleNavigate(view, send);
    }
    // Prompts actions
    else if (action === "select_prompt" && payload?.row) {
      const row = payload.row as { name: string };
      this.selectedPrompt = row.name;
      this.editingPrompt = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "edit_prompt") {
      this.editingPrompt = true;
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "cancel_edit") {
      this.editingPrompt = false;
      this.editingSkill = false;
      this.editBuffer = null;
      await this.handleNavigate(this.currentView, send);
    } else if (action === "prompt_content_change" && payload?.value) {
      this.editBuffer = payload.value as string;
    } else if (action === "save_prompt" && this.selectedPrompt && this.editBuffer) {
      await updatePromptTool.execute({
        name: this.selectedPrompt,
        content: this.editBuffer,
        commitMessage: `Update ${this.selectedPrompt} via UI`,
      });
      this.editingPrompt = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "select_commit" && payload?.hash) {
      // Preview commit - could show diff in future
      console.log("Selected commit:", payload.hash);
    }
    // Skills actions
    else if (action === "select_skill" && payload?.row) {
      const row = payload.row as { name: string };
      // Extract skill name (remove emoji prefix)
      const name = row.name.replace(/^[^\s]+\s+/, "");
      this.selectedSkill = name;
      this.editingSkill = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/skills", send);
    } else if (action === "edit_skill") {
      this.editingSkill = true;
      await this.handleNavigate("settings/skills", send);
    } else if (action === "skill_content_change" && payload?.value) {
      this.editBuffer = payload.value as string;
    } else if (action === "save_skill" && this.selectedSkill && this.editBuffer) {
      await updateSkillTool.execute({
        name: this.selectedSkill,
        content: this.editBuffer,
      });
      this.editingSkill = false;
      this.editBuffer = null;
      await this.handleNavigate("settings/skills", send);
    } else if (action === "toggle_skill" && this.selectedSkill) {
      const skillsResult = await listSkillsTool.execute({});
      const skill = skillsResult.skills?.find((s: { name: string }) => s.name === this.selectedSkill);
      if (skill) {
        await toggleSkillTool.execute({
          name: this.selectedSkill,
          enabled: !skill.enabled,
        });
        await this.handleNavigate("settings/skills", send);
      }
    } else if (action === "create_skill") {
      // Show create skill modal
      const modal = generateCreateSkillModal();
      send({ type: "a2ui", surface_id: "modal", components: modal.components, root_id: modal.root_id });
    } else if (action === "submit_create_skill" && payload) {
      const name = payload.name as string;
      const description = payload.description as string;
      const emoji = payload.emoji as string | undefined;
      const triggersStr = payload.triggers as string | undefined;
      const content = payload.content as string | undefined;
      const triggers = triggersStr ? triggersStr.split(",").map(t => t.trim()).filter(Boolean) : undefined;

      await createSkillTool.execute({ name, description, emoji, triggers, content });
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/skills", send);
    }
    // Evolution actions
    else if (action === "tab_change" && payload?.tab) {
      type EvolutionTab = "overview" | "traces" | "evaluations" | "benchmark" | "suggestions";
      this.evolutionTab = payload.tab as EvolutionTab;
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "traces_page_change" && payload?.page !== undefined) {
      this.tracesPage = payload.page as number;
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "view_trace" && payload?.row) {
      const row = payload.row as { id: string };
      const traceId = row.id.length === 8 ? this.findFullTraceId(row.id) : row.id;
      if (traceId) {
        const trace = getTrace(traceId);
        if (trace) {
          const modal = generateTraceDetailModal({
            id: trace.id,
            sessionId: trace.session_id,
            timestamp: trace.timestamp,
            userMessage: trace.user_message,
            agentResponse: trace.agent_response,
            toolCalls: trace.tool_calls ? JSON.parse(trace.tool_calls) : undefined,
            durationMs: trace.duration_ms || undefined,
          });
          send({ type: "a2ui", surface_id: "modal", components: modal.components, root_id: modal.root_id });
        }
      }
    } else if (action === "view_evaluation" && payload?.row) {
      const row = payload.row as { id: string; traceId: string };
      const evalId = row.id.length === 8 ? this.findFullEvaluationId(row.id) : row.id;
      if (evalId) {
        const evaluation = getEvaluation(evalId);
        if (evaluation) {
          const modal = generateEvaluationDetailModal({
            id: evaluation.id,
            traceId: evaluation.trace_id,
            timestamp: evaluation.timestamp,
            scores: JSON.parse(evaluation.scores),
            overallScore: evaluation.overall_score,
            feedback: evaluation.feedback || undefined,
            issues: evaluation.issues ? JSON.parse(evaluation.issues) : undefined,
          });
          send({ type: "a2ui", surface_id: "modal", components: modal.components, root_id: modal.root_id });
        }
      }
    } else if (action === "view_test_case" && payload?.row) {
      const row = payload.row as { id: string };
      const testId = row.id.length === 8 ? this.findFullTestCaseId(row.id) : row.id;
      if (testId) {
        const testCase = getTestCase(testId);
        if (testCase) {
          const modal = generateTestCaseDetailModal({
            id: testCase.id,
            category: testCase.category,
            query: testCase.query,
            context: testCase.context ? JSON.parse(testCase.context) : undefined,
            expected: JSON.parse(testCase.expected),
          });
          send({ type: "a2ui", surface_id: "modal", components: modal.components, root_id: modal.root_id });
        }
      }
    } else if (action === "view_suggestion" && payload?.row) {
      const row = payload.row as { id: string };
      const suggId = row.id.length === 8 ? this.findFullSuggestionId(row.id) : row.id;
      if (suggId) {
        const suggestion = getSuggestion(suggId);
        if (suggestion) {
          const modal = generateSuggestionDetailModal({
            id: suggestion.id,
            timestamp: suggestion.timestamp,
            type: suggestion.type,
            target: suggestion.target,
            currentValue: suggestion.current_value || undefined,
            suggestedValue: suggestion.suggested_value,
            rationale: suggestion.rationale || undefined,
            status: suggestion.status,
            validationResults: suggestion.validation_results ? JSON.parse(suggestion.validation_results) : undefined,
          });
          send({ type: "a2ui", surface_id: "modal", components: modal.components, root_id: modal.root_id });
        }
      }
    } else if (action === "create_test_case") {
      const modal = generateCreateTestCaseModal();
      send({ type: "a2ui", surface_id: "modal", components: modal.components, root_id: modal.root_id });
    } else if (action === "submit_create_test_case" && payload) {
      const category = payload.category as string;
      const query = payload.query as string;
      const minScore = payload.minScore ? Number(payload.minScore) : undefined;
      const shouldMentionStr = payload.shouldMention as string | undefined;
      const shouldNotMentionStr = payload.shouldNotMention as string | undefined;

      const id = crypto.randomUUID();
      insertTestCase({
        id,
        category,
        query,
        expected: {
          minScore,
          shouldMention: shouldMentionStr ? shouldMentionStr.split(",").map(s => s.trim()).filter(Boolean) : undefined,
          shouldNotMention: shouldNotMentionStr ? shouldNotMentionStr.split(",").map(s => s.trim()).filter(Boolean) : undefined,
        },
      });

      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "delete_test_case" && payload?.id) {
      deleteTestCase(payload.id as string);
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "apply_suggestion" && payload?.id) {
      updateSuggestionStatus(payload.id as string, "applied");
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "reject_suggestion" && payload?.id) {
      updateSuggestionStatus(payload.id as string, "rejected");
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "test_suggestion" && payload?.id) {
      updateSuggestionStatus(payload.id as string, "testing");
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/evolution", send);
    } else if (action === "close_modal") {
      send({ type: "clear_surface", surface_id: "modal" });
    } else if (action === "revert_prompt" && this.selectedPrompt) {
      // Show revert modal with commit history
      const historyResult = await getPromptHistoryTool.execute({ name: this.selectedPrompt, limit: 20 });
      if (historyResult.success && historyResult.commits) {
        const modal = generatePromptRevertModal(this.selectedPrompt, historyResult.commits);
        send({ type: "a2ui", surface_id: "modal", components: modal.components, root_id: modal.root_id });
      }
    } else if (action === "select_revert_commit" && payload?.commit && this.selectedPrompt) {
      const commit = payload.commit as { hash: string };
      await revertPromptTool.execute({ name: this.selectedPrompt, commitHash: commit.hash });
      send({ type: "clear_surface", surface_id: "modal" });
      await this.handleNavigate("settings/prompts", send);
    } else if (action === "run_benchmark") {
      // Show toast that benchmark is starting
      const toast = generateToast("Running benchmark tests... This may take a while.", "info");
      send({ type: "a2ui", surface_id: "toast", components: toast.components, root_id: toast.root_id });

      // Run benchmarks in background (simplified - in production would use actual evaluator)
      const tests = listTestCases({ limit: 100 });
      for (const test of tests) {
        // For each test, we would normally call the agent and evaluate
        // For now, just simulate by sending progress toast
        console.log(`Running test: ${test.id} - ${test.query.slice(0, 50)}`);
      }

      // Show completion toast
      setTimeout(() => {
        const doneToast = generateToast(`Completed ${tests.length} benchmark tests`, "success");
        send({ type: "a2ui", surface_id: "toast", components: doneToast.components, root_id: doneToast.root_id });
      }, 1000);
    } else if (action === "run_test_case" && payload?.id) {
      const toast = generateToast("Running test case...", "info");
      send({ type: "a2ui", surface_id: "toast", components: toast.components, root_id: toast.root_id });
      send({ type: "clear_surface", surface_id: "modal" });
      console.log(`Running test case: ${payload.id}`);
    }
    // Default - pass to agent
    else {
      const message = `[Action: ${action}] ${payload ? JSON.stringify(payload) : ""}`;
      await this.handleUserMessage(message, send);
    }
  }

  // Helper methods to find full IDs from truncated IDs
  private findFullTraceId(shortId: string): string | null {
    const traces = listTraces({ limit: 100 });
    const found = traces.find(t => t.id.startsWith(shortId));
    return found?.id || null;
  }

  private findFullEvaluationId(shortId: string): string | null {
    const evals = listEvaluations({ limit: 100 });
    const found = evals.find(e => e.id.startsWith(shortId));
    return found?.id || null;
  }

  private findFullTestCaseId(shortId: string): string | null {
    const tests = listTestCases({ limit: 100 });
    const found = tests.find(t => t.id.startsWith(shortId));
    return found?.id || null;
  }

  private findFullSuggestionId(shortId: string): string | null {
    const suggs = listSuggestions({ limit: 100 });
    const found = suggs.find(s => s.id.startsWith(shortId));
    return found?.id || null;
  }

  private handleAgentEvent(event: any, send: (msg: unknown) => void): void {
    switch (event.type) {
      case "message_start":
      case "message_update":
        // Stream partial content
        if (event.message.role === "assistant") {
          const content = event.message.content;
          let text = "";
          for (const block of content) {
            if (block.type === "text") {
              text += block.text;
            }
          }
          this.streamingContent = text;
          this.sendChatUpdate(send);
          // Also send simple text format for TUI clients
          send({ type: "agent_text", content: text, is_final: false });
        }
        break;

      case "message_end":
        if (event.message.role === "assistant") {
          const content = event.message.content;
          let text = "";
          for (const block of content) {
            if (block.type === "text") {
              text += block.text;
            }
          }
          // Add final message to chat history
          this.chatMessages.push({ role: "assistant", content: text });
          this.isStreaming = false;
          this.streamingContent = "";
          this.sendChatUpdate(send);
          // Also send simple text format for TUI clients
          send({ type: "agent_text", content: text, is_final: true });
        }
        break;

      case "tool_execution_start":
        // Add tool call indicator to chat
        this.chatMessages.push({ role: "tool", content: `Using ${event.toolName}...` });
        this.sendChatUpdate(send);
        // Also send tool_call for TUI clients
        send({ type: "tool_call", tool: event.toolName });
        break;

      case "tool_execution_end":
        // Tool completed - no need to add to chat, agent will respond
        break;

      case "agent_end":
        this.isStreaming = false;
        this.sendChatUpdate(send);
        break;
    }
  }

}

// WebSocket data type
interface WSData {
  sessionId: string;
  config: GatewayConfig;
}

// Content type helper
function getContentType(filePath: string): string {
  const ext = filePath.split(".").pop()?.toLowerCase();
  const types: Record<string, string> = {
    html: "text/html",
    js: "application/javascript",
    css: "text/css",
    json: "application/json",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    svg: "image/svg+xml",
    ico: "image/x-icon",
    woff: "font/woff",
    woff2: "font/woff2",
    ttf: "font/ttf",
  };
  return types[ext || ""] || "application/octet-stream";
}

/**
 * Start the Gateway server with Bun
 */
export function startGateway(config: GatewayConfig & { webDir?: string } = {}): void {
  const port = config.port || 8000;
  const app = createGatewayApp();
  const sessions = new Map<string, GatewaySession>();
  const webDir = config.webDir;

  Bun.serve<WSData>({
    port,
    async fetch(req, server) {
      const url = new URL(req.url);

      // Upgrade WebSocket connections
      if (url.pathname === "/ws") {
        const sessionId = crypto.randomUUID();
        const success = server.upgrade(req, {
          data: { sessionId, config },
        });
        if (success) {
          return undefined;
        }
        return new Response("WebSocket upgrade failed", { status: 400 });
      }

      // Serve static files from web directory
      if (webDir) {
        let filePath = url.pathname;
        if (filePath === "/" || filePath === "") {
          filePath = "/index.html";
        }

        const fullPath = webDir + filePath;
        const file = Bun.file(fullPath);

        if (await file.exists()) {
          const contentType = getContentType(filePath);
          return new Response(file, {
            headers: { "Content-Type": contentType },
          });
        }

        // SPA fallback - serve index.html for non-API routes
        if (!filePath.startsWith("/api") && !filePath.startsWith("/mcp") && !filePath.startsWith("/health")) {
          const indexFile = Bun.file(webDir + "/index.html");
          if (await indexFile.exists()) {
            return new Response(indexFile, {
              headers: { "Content-Type": "text/html" },
            });
          }
        }
      }

      // Handle HTTP requests with Hono
      return app.fetch(req);
    },
    websocket: {
      open(ws) {
        const { sessionId, config: wsConfig } = ws.data;
        const session = new GatewaySession(wsConfig);
        sessions.set(sessionId, session);
        console.log(`WebSocket connected: ${sessionId}`);
      },
      async message(ws, message) {
        const { sessionId } = ws.data;
        const session = sessions.get(sessionId);
        if (!session) return;

        try {
          const data = JSON.parse(message.toString());
          await session.handleMessage(data, (msg) => {
            ws.send(JSON.stringify(msg));
          });
        } catch (error) {
          console.error("WebSocket message error:", error);
          ws.send(JSON.stringify({
            type: "error",
            code: "parse_error",
            message: "Failed to parse message",
          }));
        }
      },
      close(ws) {
        const { sessionId } = ws.data;
        sessions.delete(sessionId);
        console.log(`WebSocket disconnected: ${sessionId}`);
      },
    },
  });

  console.log(`PHA Gateway running at http://localhost:${port}`);
  console.log(`WebSocket available at ws://localhost:${port}/ws`);
}

// Legacy export for compatibility
export const createGateway = createGatewayApp;
