/**
 * GitHub Issues Integration
 *
 * Creates GitHub issues from diagnose results using the `gh` CLI.
 */

import { execSync } from 'child_process';
import type { DiagnoseWeakness } from './diagnose.js';

export interface GitHubIssueResult {
  number: number;
  url: string;
}

/**
 * Create a GitHub issue using `gh` CLI
 */
export async function createGitHubIssue(opts: {
  title: string;
  body: string;
  labels?: string[];
}): Promise<GitHubIssueResult> {
  const { title, body, labels = [] } = opts;

  const labelFlags = labels.map((l) => `--label "${l}"`).join(' ');

  // Escape title for shell
  const escapedTitle = title.replace(/"/g, '\\"');

  const cmd = `gh issue create --title "${escapedTitle}" --body-file - ${labelFlags}`;

  const output = execSync(cmd, {
    encoding: 'utf-8',
    timeout: 30000,
    input: body,
    stdio: ['pipe', 'pipe', 'pipe'],
  }).trim();

  // gh issue create outputs the URL like: https://github.com/owner/repo/issues/123
  const urlMatch = output.match(/https:\/\/github\.com\/[^/]+\/[^/]+\/issues\/(\d+)/);
  if (urlMatch) {
    return {
      number: parseInt(urlMatch[1], 10),
      url: urlMatch[0],
    };
  }

  // Fallback: try to parse issue number from output
  const numMatch = output.match(/\/issues\/(\d+)/);
  return {
    number: numMatch ? parseInt(numMatch[1], 10) : 0,
    url: output,
  };
}

/**
 * Build structured issue body from a diagnose weakness
 */
export function buildDiagnoseIssueBody(weakness: DiagnoseWeakness): string {
  const lines: string[] = [];

  lines.push(`## Category: ${weakness.label}`);
  lines.push('');
  lines.push(`**Score:** ${weakness.score.toFixed(1)}/100 (${weakness.gap.toFixed(1)} points below threshold)`);
  lines.push('');

  // Failing tests
  if (weakness.failingTests.length > 0) {
    lines.push(`### Failing Tests (${weakness.failingTests.length})`);
    lines.push('');

    for (const test of weakness.failingTests.slice(0, 10)) {
      lines.push(`#### \`${test.testCaseId}\` — Score: ${test.score}/100`);
      if (test.feedback) {
        lines.push(`> ${test.feedback.substring(0, 200)}${test.feedback.length > 200 ? '...' : ''}`);
      }
      if (test.issues.length > 0) {
        for (const issue of test.issues) {
          lines.push(`- **[${issue.severity}]** ${issue.type}: ${issue.description}`);
        }
      }
      lines.push('');
    }

    if (weakness.failingTests.length > 10) {
      lines.push(`_...and ${weakness.failingTests.length - 10} more failing tests_`);
      lines.push('');
    }
  }

  // Common patterns
  if (weakness.commonPatterns.length > 0) {
    lines.push('### Common Failure Patterns');
    lines.push('');
    for (const pattern of weakness.commonPatterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push('');
  }

  // Suggested fix
  lines.push('### Suggested Actions');
  lines.push('');
  lines.push('- [ ] Review failing test feedback above');
  lines.push('- [ ] Update `src/prompts/SOUL.md` for category-specific improvements');
  lines.push('- [ ] Create/update relevant skill in `src/skills/`');
  lines.push('- [ ] Run `pha eval benchmark` to verify improvement');
  lines.push('');
  lines.push('---');
  lines.push('_Auto-generated by PHA Evolution Diagnose System_');

  return lines.join('\n');
}

/**
 * Check if `gh` CLI is available and authenticated
 */
export function isGitHubCLIAvailable(): boolean {
  try {
    execSync('gh auth status', {
      encoding: 'utf-8',
      timeout: 10000,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return true;
  } catch {
    return false;
  }
}
